export const BOOK_TAGS = [
    "Ficção",
    "Não-ficção",
    "Romance",
    "Fantasia",
    "Ficção Científica",
    "Mistério",
    "Suspense",
    "Terror",
    "Aventura",
    "Histórico",
    "Biografia",
    "Autoajuda",
    "Filosofia",
    "Psicologia",
    "Negócios",
    "Poesia",
    "Drama",
    "Comédia",
    "Jovem Adulto",
    "Infantil",
    "Clássico",
    "Policial",
    "Distopia",
    "Romance de Época",
    "Literatura Brasileira",
    "Literatura Estrangeira"
];
